name: PR

on:
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        node: # https://nodejs.org/en/about/releases/
          - '*' # Current
          - '12' # Active LTS
          - '10' # Maintenance LTS
      fail-fast: false

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: test-matrix-npm-cache
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-${{ matrix.node }}-build-${{ env.cache-name }}-
            npm-${{ runner.os }}-build-${{ env.cache-name }}-
            npm-${{ runner.os }}-build-
            npm-${{ runner.os }}-
            npm-

      - name: Install dependencies
        run: |
          npm i --prefer-offline --no-audit
          npm list --depth=0 || true

      - name: Run Tests
        run: npm run test
