name: PR

on:
  pull_request:
    branches:
      - master

# Only tests for last head of the branch need to pass, others irrelevant
concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    uses: hertzg/node-xhb/.github/workflows/_test-matrix.yml@master
    with:
      fail-fast: false # we need to run all tests to help find issues

  pack:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: |
          contents=$(jq -r ".version += \"-${PREID}+$(git rev-parse --short HEAD)\"" ./package.json) && echo "$contents" > ./package.json
          npm version --no-git-tag-version --allow-same-version "$(jq -r ".version" ./package.json)"
          npm run build
          mkdir pack/
          npm pack --pack-destination pack/
        env:
          PREID: |
            pr${{ github.event.pull_request.number }}.${{github.run_id}}${{github.run_number}}${{github.run_attempt}}
      - uses: actions/upload-artifact@v2
        with:
          name: pr${{ github.event.pull_request.number }}-artifacts
          path: |
            pack/
            dist/
