name: PR

on:
  pull_request:
    branches:
      - master

# Only tests for last head of the branch need to pass, others irrelevant
concurrency:
  group: '${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: lts/*
      - uses: bahmutov/npm-install@v1
      - run: npm run build
      - run: |
          mkdir pack/
          cd pack/
          npm pack ../
      - uses: actions/upload-artifact@v2
        with:
          name: pack
          path: |
            pack/*
            dist/*

  test:
    uses: hertzg/node-xhb/.github/workflows/_test-matrix.yml@master
    with:
      fail-fast: false # we need to run all tests to help find issues
