name: PR

on:
  pull_request:
    branches:
      - master

# Only tests for last head of the branch need to pass, others irrelevant
concurrency: 
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: hertzg/node-xhb/.github/workflows/reusable/test-matrix.yml@master
    with:
      fail-fast: false # we need to run all tests to help find issues

