name: PR

on:
  pull_request:
    branches:
      - master

# Only tests for last head of the branch need to pass, others irrelevant
concurrency:
  group: "${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  test:
    uses: hertzg/node-xhb/.github/workflows/_test-matrix.yml@master
    with:
      fail-fast: false # we need to run all tests to help find issues

  pack:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          check-latest: true
          node-version: ${{ matrix.node }}
      - uses: bahmutov/npm-install@v1
      - run: |
          npm version major --no-git-tag-version
          VERSION_APPEND="-pr$PR_ID.$RUN_ID$RUN_NUMBER$RUN_ATTEMPT+$(git rev-parse --short HEAD)"
          jq ".version += \"-$(VERSION_APPEND)\"" ./package.json > ./package.json
          npm run build
          mkdir pack/
          npm pack --pack-destination pack/
        env:
          PR_ID: ${{ github.event.pull_request.number }}
          RUN_ID: ${{ github.run_id }}
          RUN_NUMBER: ${{ github.run_number }}
          RUN_ATTEMPT: ${{ github.run_attempt }}
      - uses: actions/upload-artifact@v2
        with:
          name: pr${{ github.event.pull_request.number }}-artifacts
          path: |
            pack/
            dist/
