name: Release

on:
  push:
    branches:
      - master

# We only want to have last workflow run and cancel any previous in progress ones
concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  test:
    uses: hertzg/node-xhb/.github/workflows/_test-matrix.yml@master
    with:
      fail-fast: true # if any fail, fail fast and stop release process

  release:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository == 'hertzg/node-xhb' }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          check-latest: true
          node-version: lts/*
      - run: yarn
      - run: yarn run build
      - run: yarn dlx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
